### ISSUE TITLE
Reduce motion sickness

### ISSUE THREAD

**Issue by MrRedstoneToGo** [der-fruhling-entertainment/create-train-perspective#47]
**Is your feature request related to a problem? Please describe.**
It bothers me that whenever you stand in the train and drive around a bend, everything shakes extremely.

**Describe the solution you'd like**
Reduce it to half. It's quite disturbing, but not so exaggerated.

**Additional context**
You could also add that players who are not sitting in the train are pushed forward when the train brakes and backwards when the train accelerates.

**Comment by der-fruhling** [comment]
> **Is your feature request related to a problem? Please describe.**
> It bothers me that whenever you stand in the train and drive around a bend, everything shakes extremely.

Could you please put here the version of the mod you are using? I believe this was fixed in #22.

> **Additional context**
> You could also add that players who are not sitting in the train are pushed forward when the train brakes and backwards when the train accelerates.

While this is certainly an interesting idea, it would greatly change how the player moves on a train while standing, which is probably out-of-scope for this mod as it primary focuses on moving the camera. Plus, such a thing would probably require a server-side mod, while this mod is trying to stay client-side only.

Such a feature could be in a separate mod that can be installed on both sides.

**Comment by MrRedstoneToGo** [comment]
I am using the latest version on Modrinth, v0.3.1, and as mod loader fabric.

You say on the website that the mod causes motion sickness (when you stand, not when you sit), which I don't think is a bad thing in itself and is not meant as a bug in my opinion, but should encourage players to sit down on the train! I just find the effect very strong and would reduce it.

**Comment by der-fruhling** [comment]
I've done some testing and find that the camera does not properly lean when a train travels over a slope, instead staying in the same orientation (as if the mod was not installed) but keeping the roll. This causes things to appear as if it's rotating around the player.

I believe this is the issue you are experiencing, correct?

**Comment by MrRedstoneToGo** [comment]
What I'm trying to explain to you is **NOT** an **ISSUE**. So, again: You build a train. Then you build the track for it, preferably any track with lots of horizontal curves (curves with the ends at the same height). Now you drive the train or are driven by an animal. It is important that you _do not_ sit on a seat! Whenever the train goes around the curve, the view shakes to match the train's direction of travel. I would like to see this shaking reduced somewhat. It's still a bit exaggerated so far.

**Comment by der-fruhling** [comment]
Thanks for explaining further and sorry for my misunderstanding, I am able to reproduce this correctly now.

As the seated perspective is smooth, I don't think it's reasonable to try and _reduce_ the shaking effect instead of making it consistent with the sitting behavior. My suggested resolution is to smooth it out entirely. I'm going to add it to the board with this goal in mind for now.

Perhaps there could be a config option to enable a toned-down version of this effect in the future?

**Comment by MrRedstoneToGo** [comment]
I thought this shake effect was there to get players to sit down on the train and found this "punishment" for not sitting down a bit too strong.

**Comment by der-fruhling** [comment]
The real cause of this is probably that it's updating data every tick, but actually uses that data every frame without doing any interpolation like vanilla does. Probably an artifact of some older code in this repo. (then again, I have not looked at this just yet)

Plus, imo Create punishes players enough for riding trains without sitting down by simply not attaching them to the train very well. Flying off a high-speed train is probably enough to convince players that seats are important, at least until this is fixed in Create (if at all).

**Comment by der-fruhling** [comment]
Considering this closed as of #54.
